In [1]:
import numpy as np

In [2]:
x = [1, 2, 3]

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
i = 25

In [5]:
print(i)

25


In [6]:
for i in x:
    print(i)

1
2
3


In [7]:
i

3

In [8]:
a_list = list(range(10, 20))
b_list = list(range(20, 30))

In [9]:
def add_list_elements(a, b):
    c = []
    for i in range(len(a)):
        print(a[i], b[i])
        c.append(a[i] + b[i])
    return c

In [10]:
add_list_elements(a_list, b_list)

10 20
11 21
12 22
13 23
14 24
15 25
16 26
17 27
18 28
19 29


[30, 32, 34, 36, 38, 40, 42, 44, 46, 48]

In [11]:
a_list + b_list

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [12]:
a_array = np.array(a_list)
b_array = np.array(b_list)

In [13]:
a_array + b_array

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [14]:
np.array

<function numpy.core.multiarray.array>

In [15]:
np.array?

In [16]:
print(a_array)

[10 11 12 13 14 15 16 17 18 19]


In [17]:
print(b_array)

[20 21 22 23 24 25 26 27 28 29]


In [18]:
%timeit a_array + b_array #faster

452 ns ± 8.44 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
